{% set name = "jupyterlab-blockly" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_blockly-{{ version }}.tar.gz
  sha256: cab7bd513f204b2689978822a58a0dfcb232391822e53fe1007e999eda77c974

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - jupyterlab_blockly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantstack/jupyterlab-blockly
  summary: Blockly extension for JupyterLab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
